apiVersion: v1
kind: Service
metadata:
  name: {{ include "orion-context-broker-ld.fullname" . }}
  labels:
    {{- include "orion-context-broker-ld.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "orion-context-broker-ld.selectorLabels" . | nindent 4 }}
